Tweak error message in mps
Give more info to a user who is trying to load a nonexistent playlist.

diff --git a/bin/mps b/bin/mps
--- a/bin/mps
+++ b/bin/mps
@@ -144,6 +144,7 @@ case "$1" in
 			# play the playlist
 			mpc -q play
 		else
+			echo "Playlist '$1' not found in playlist directory: $playlistdir" >&2
 			echo "$usage" >&2
 		fi
 	;;
